version: '3.4'

services:

  apache:
    build:
      dockerfile: compose/Dockerfile
    ports:
      - "80:80"
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      rabbitmq:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      RABBITMQ_HOST: rabbitmq
      GIT_COMMIT_NAME: ${GIT_COMMIT_NAME:-}
      GIT_COMMIT_EMAIL: ${GIT_COMMIT_EMAIL:-}
    volumes:
      - ./:/var/www/html/
      - mysql_client_binaries:/usr/bin/mysql_client_binaries

  mysql:
    image: mysql:8.0.29-debian
    command:
      --default-authentication-plugin=mysql_native_password
      --sql_mode=ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb_buffer_pool_size=2147483648
      --wait_timeout=31536000
    ports:
      - "3306:3306"
    environment:
      TZ: Europe/Berlin
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-custom}
      MYSQL_USER: ${MYSQL_USER:-custom}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-custom}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-custom}
      MYSQL_DUMP: ${MYSQL_DUMP}
      GH_TOKEN: ${GH_TOKEN}
    volumes:
      - ./compose/mysql/docker-entrypoint.sh:/usr/local/bin/custom-entrypoint.sh:ro
      - ./sql/:/docker-entrypoint-initdb.d/custom/
      - ./.git/config:/docker-entrypoint-initdb.d/.gitconfig:ro
      - mysql_client_binaries:/usr/bin/volumed
    healthcheck:
      test: mysqladmin ping && [ -f /var/lib/mysql/init.done ]
      start_period: 7m
      interval: 5s
    entrypoint: /usr/local/bin/custom-entrypoint.sh

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    ports:
      - "15672:15672"
    volumes:
      - ./compose/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./compose/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 20s
      retries: 10
    command: rabbitmq-server

volumes:
  mysql_client_binaries: